import { randomUUID } from 'node:crypto';
function clone(value){return structuredClone(value);}

export async function setup(ctx){
  const registerUsableItem=ctx.exports.get('pm-inventory','registerUsableItem');
  const apps=new Map(),messages=new Map(),calls=new Map();
  for(const app of [{id:'contacts',label:'Contacts',icon:'contacts',order:10},{id:'messages',label:'Messages',icon:'messages',order:20},{id:'calls',label:'Calls',icon:'phone',order:30},{id:'mail',label:'Mail',icon:'mail',order:40}])apps.set(app.id,app);

  ctx.exports.register('registerApp',definition=>{if(!definition?.id||!definition?.label)throw new Error('Phone app requires id and label.');apps.set(definition.id,clone(definition));});
  ctx.exports.register('listApps',()=>[...apps.values()].sort((a,b)=>(a.order||100)-(b.order||100)).map(clone));

  const requirePhone=actorId=>{if(!ctx.host.hasItemTemplate(actorId,'phone.basic'))throw new Error('You do not have your phone with you.');};
  const inboxFor=actorId=>messages.get(actorId)??[];
  const pushMessage=(actorId,row)=>{const inbox=inboxFor(actorId);inbox.push(row);if(inbox.length>200)inbox.splice(0,inbox.length-200);messages.set(actorId,inbox);};
  const publicCall=call=>{if(!call)return null;const {timer,...safe}=call;return clone(safe);};
  const sendCall=call=>{const wire=publicCall(call);ctx.host.send(call.callerId,'phone_call',wire);ctx.host.send(call.calleeId,'phone_call',wire);};
  const clearCall=call=>{clearTimeout(call.timer);calls.delete(call.callerId);calls.delete(call.calleeId);};
  const finishCall=async(call,status,reason)=>{if(!call||!calls.has(call.callerId))return;call.status=status;call.endedAt=Date.now();sendCall(call);clearCall(call);await ctx.events.emit('phone:callEnded',{callId:call.id,reason},{actorId:call.callerId,roomId:ctx.host.getPlayer(call.callerId)?.roomId});};
  const phoneState=actorId=>{const player=ctx.host.getPlayer(actorId);if(!player)return null;const contacts=ctx.host.listOnlinePlayers().filter(p=>p.id!==actorId).map(p=>({name:p.name,phoneNumber:p.phoneNumber,online:true}));return {owner:{name:player.name,phoneNumber:player.phoneNumber},apps:[...apps.values()].sort((a,b)=>(a.order||100)-(b.order||100)).map(clone),contacts,messages:inboxFor(actorId).slice(-80),activeCall:publicCall(calls.get(actorId))};};

  registerUsableItem('phone.basic',async({action})=>{const result=await action.execute('phone:open',{actorId:action.actorId,roomId:action.roomId,source:'resource',payload:{}});if(!result.ok)throw new Error(result.reason);return result.value;});

  ctx.actions.register('phone:open',async action=>{requirePhone(action.actorId);const state=phoneState(action.actorId);if(!state)throw new Error('Phone owner is unavailable.');ctx.host.send(action.actorId,'phone_open',state);await action.emit('phone:opened',{appCount:state.apps.length},{roomId:action.roomId});return state;});
  ctx.actions.register('phone:sendMessage',async(action,payload)=>{requirePhone(action.actorId);const sender=ctx.host.getPlayer(action.actorId),target=ctx.host.findPlayerByPhone(String(payload?.to||'')),text=String(payload?.text||'').trim().replace(/\s+/g,' ').slice(0,500);if(!sender||!target)throw new Error('That number is unavailable.');if(!ctx.host.hasItemTemplate(target.id,'phone.basic'))throw new Error('That phone is unavailable.');if(!text)throw new Error('Message cannot be empty.');const row={id:randomUUID(),from:sender.phoneNumber,fromName:sender.name,to:target.player.phoneNumber,text,sentAt:Date.now()};pushMessage(action.actorId,row);pushMessage(target.id,row);ctx.host.send(target.id,'phone_message',row);ctx.host.send(action.actorId,'phone_message',row);await action.emit('phone:messageSent',{to:target.player.phoneNumber,length:text.length},{roomId:action.roomId});return row;});

  ctx.actions.register('phone:startCall',async(action,payload)=>{requirePhone(action.actorId);const caller=ctx.host.getPlayer(action.actorId),target=ctx.host.findPlayerByPhone(String(payload?.to||''));if(!caller||!target||target.id===action.actorId)throw new Error('That number is unavailable.');if(!ctx.host.hasItemTemplate(target.id,'phone.basic'))throw new Error('That phone is unavailable.');if(calls.has(action.actorId)||calls.has(target.id))throw new Error('One of the phones is already in a call.');const call={id:randomUUID(),callerId:action.actorId,callerName:caller.name,callerNumber:caller.phoneNumber,calleeId:target.id,calleeName:target.player.name,calleeNumber:target.player.phoneNumber,status:'ringing',startedAt:Date.now(),transcript:[],timer:null};call.timer=setTimeout(()=>void finishCall(call,'missed','no-answer').catch(error=>console.error('[phone] ring timeout failed',error)),30000);call.timer.unref?.();calls.set(action.actorId,call);calls.set(target.id,call);sendCall(call);ctx.host.send(target.id,'phone_alert',{type:'incoming_call',call:publicCall(call)});await action.emit('phone:callStarted',{to:target.player.phoneNumber},{roomId:action.roomId});return publicCall(call);});
  ctx.actions.register('phone:answerCall',async action=>{requirePhone(action.actorId);const call=calls.get(action.actorId);if(!call||call.status!=='ringing'||call.calleeId!==action.actorId)throw new Error('There is no incoming call to answer.');clearTimeout(call.timer);call.timer=null;call.status='connected';call.answeredAt=Date.now();sendCall(call);await action.emit('phone:callAnswered',{callId:call.id},{roomId:action.roomId});return publicCall(call);});
  ctx.actions.register('phone:declineCall',async action=>{requirePhone(action.actorId);const call=calls.get(action.actorId);if(!call||call.status!=='ringing'||call.calleeId!==action.actorId)throw new Error('There is no ringing call to decline.');await finishCall(call,'declined','declined');return {ended:true};});
  ctx.actions.register('phone:sendCallText',async(action,payload)=>{requirePhone(action.actorId);const call=calls.get(action.actorId),sender=ctx.host.getPlayer(action.actorId),text=String(payload?.text||'').trim().replace(/\s+/g,' ').slice(0,500);if(!call||call.status!=='connected'||!sender)throw new Error('You are not in a connected call.');if(!text)throw new Error('Call text cannot be empty.');const line={id:randomUUID(),fromId:action.actorId,fromName:sender.name,text,sentAt:Date.now()};call.transcript.push(line);if(call.transcript.length>100)call.transcript.shift();ctx.host.send(call.callerId,'phone_call_text',line);ctx.host.send(call.calleeId,'phone_call_text',line);await action.emit('phone:callText',{callId:call.id,length:text.length},{roomId:action.roomId});return line;});
  ctx.actions.register('phone:endCall',async action=>{requirePhone(action.actorId);const call=calls.get(action.actorId);if(!call)throw new Error('There is no active call.');await finishCall(call,'ended','hangup');return {ended:true};});

  ctx.events.on('player:left',event=>{if(!event.actorId)return;messages.delete(event.actorId);const call=calls.get(event.actorId);if(call)void finishCall(call,'ended','disconnected').catch(error=>console.error('[phone] disconnect cleanup failed',error));});
  ctx.lifecycle.onDispose(()=>{const unique=new Set(calls.values());for(const call of unique)clearTimeout(call.timer);calls.clear();messages.clear();});
  ctx.heartbeat.snapshot('apps',()=>[...apps.values()].map(app=>({id:app.id,label:app.label})));
}
